name: smart_dev_flutter_cast_example
description: "Demonstrates how to use the smart_dev_flutter_cast plugin."

publish_to: "none"

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  smart_dev_flutter_cast:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
